import {NextResponse} from "next/server";
import {getCurrentUser} from "@/lib/auth";
import {prisma} from "@/lib/prisma";
import {encryptJson} from "@/lib/integration-crypto";
const providers=["GOOGLE_SHEETS","SLACK","DISCORD","TELEGRAM","WEBHOOK"];
export async function GET(){const u=await getCurrentUser();if(!u)return NextResponse.json({error:"Authentication required."},{status:401});const rows=await prisma.integrationConnection.findMany({where:{creatorId:u.id},select:{id:true,name:true,provider:true,status:true,metadata:true,createdAt:true,updatedAt:true},orderBy:{createdAt:"desc"}});return NextResponse.json({integrations:rows});}
export async function POST(req:Request){const u=await getCurrentUser();if(!u)return NextResponse.json({error:"Authentication required."},{status:401});const b=await req.json();const provider=String(b.provider||"").toUpperCase();if(!providers.includes(provider))return NextResponse.json({error:"Unsupported provider."},{status:400});const name=String(b.name||provider).trim().slice(0,100);const credentials=b.credentials&&typeof b.credentials==="object"?b.credentials:{};const metadata=b.metadata&&typeof b.metadata==="object"?b.metadata:null;const row=await prisma.integrationConnection.create({data:{creatorId:u.id,provider:provider as any,name,credentials:encryptJson(credentials),metadata:metadata?JSON.stringify(metadata):null}});return NextResponse.json({integration:{id:row.id,name:row.name,provider:row.provider,status:row.status,metadata:row.metadata}},{status:201});}
export async function PATCH(req:Request){const u=await getCurrentUser();if(!u)return NextResponse.json({error:"Authentication required."},{status:401});const b=await req.json();const id=String(b.id||"");const existing=await prisma.integrationConnection.findFirst({where:{id,creatorId:u.id}});if(!existing)return NextResponse.json({error:"Integration not found."},{status:404});const data:any={};if(b.name!==undefined)data.name=String(b.name).trim().slice(0,100);if(b.status!==undefined)data.status=String(b.status).toUpperCase();if(b.credentials!==undefined)data.credentials=encryptJson(b.credentials);if(b.metadata!==undefined)data.metadata=JSON.stringify(b.metadata);const row=await prisma.integrationConnection.update({where:{id},data});return NextResponse.json({integration:{id:row.id,name:row.name,provider:row.provider,status:row.status,metadata:row.metadata}});}
export async function DELETE(req:Request){const u=await getCurrentUser();if(!u)return NextResponse.json({error:"Authentication required."},{status:401});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Integration id is required."},{status:400});await prisma.integrationConnection.deleteMany({where:{id,creatorId:u.id}});return NextResponse.json({success:true});}
