CREATE TYPE "UserRole" AS ENUM ('CREATOR', 'ADMIN', 'CUSTOMER');
CREATE TYPE "ProductType" AS ENUM ('DIGITAL', 'COURSE', 'MEMBERSHIP');
CREATE TYPE "ProductStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'PAID', 'FAILED', 'REFUNDED');
CREATE TYPE "LessonType" AS ENUM ('VIDEO', 'TEXT', 'FILE');
CREATE TABLE "User" ("id" TEXT NOT NULL PRIMARY KEY, "email" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Session" ("id" TEXT NOT NULL PRIMARY KEY, "token" TEXT NOT NULL, "userId" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "user" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "model" null NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "code" TEXT NOT NULL, "attempts" INTEGER NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "user" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "model" null NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "username" TEXT NOT NULL, "displayName" TEXT NOT NULL, "theme" TEXT NOT NULL DEFAULT "minimal", "published" BOOLEAN NOT NULL DEFAULT false, "user" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "model" null NOT NULL PRIMARY KEY, "profileId" TEXT NOT NULL, "title" TEXT NOT NULL, "url" TEXT NOT NULL, "position" INTEGER NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "profile" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "model" null NOT NULL, "id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "profileId" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "price" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT "INR", "creator" null NOT NULL, "profile" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");
CREATE INDEX "Session_userId_code_idx" ON "Session"("userId","code");
CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");
CREATE INDEX "Session_profileId_status_idx" ON "Session"("profileId","status");
CREATE TABLE "Order" ("id" TEXT NOT NULL PRIMARY KEY, "productId" TEXT NOT NULL, "creatorId" TEXT NOT NULL, "buyerEmail" TEXT NOT NULL, "amount" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT "INR", "product" null NOT NULL, "creator" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "Order_buyerEmail_idx" ON "Order"("buyerEmail");
CREATE INDEX "Order_providerId_idx" ON "Order"("providerId");
CREATE TABLE "Course" ("id" TEXT NOT NULL PRIMARY KEY, "productId" TEXT NOT NULL, "title" TEXT NOT NULL, "product" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "model" null NOT NULL PRIMARY KEY, "courseId" TEXT NOT NULL, "title" TEXT NOT NULL, "position" INTEGER NOT NULL, "course" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "model" null NOT NULL PRIMARY KEY, "moduleId" TEXT NOT NULL, "title" TEXT NOT NULL, "position" INTEGER NOT NULL, "module" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "model" null NOT NULL PRIMARY KEY, "courseId" TEXT NOT NULL, "productId" TEXT NOT NULL, "userId" TEXT NOT NULL, "course" null NOT NULL, "product" null NOT NULL, "user" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "model" null NOT NULL, "id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "email" TEXT NOT NULL, "creator" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "Course_courseId_position_idx" ON "Course"("courseId","position");
CREATE INDEX "Course_moduleId_position_idx" ON "Course"("moduleId","position");
CREATE UNIQUE INDEX "Course_courseId_userId_key" ON "Course"("courseId","userId");
CREATE INDEX "Course_userId_idx" ON "Course"("userId");
CREATE UNIQUE INDEX "Course_creatorId_email_key" ON "Course"("creatorId","email");
CREATE INDEX "Course_creatorId_createdAt_idx" ON "Course"("creatorId","createdAt");
CREATE TABLE "LeadMagnet" ("id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "published" BOOLEAN NOT NULL DEFAULT false, "creator" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "LeadMagnet_creatorId_published_idx" ON "LeadMagnet"("creatorId","published");
CREATE TABLE "BookingSlot" ("id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "startAt" TIMESTAMP(3) NOT NULL, "endAt" TIMESTAMP(3) NOT NULL, "price" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT "INR", "available" BOOLEAN NOT NULL DEFAULT true, "creator" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "BookingSlot_creatorId_startAt_idx" ON "BookingSlot"("creatorId","startAt");
CREATE TABLE "Booking" ("id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "slotId" TEXT NOT NULL, "customerEmail" TEXT NOT NULL, "amount" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT "INR", "status" TEXT NOT NULL DEFAULT "PENDING", "creator" null NOT NULL, "slot" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "Booking_creatorId_status_idx" ON "Booking"("creatorId","status");
CREATE INDEX "Booking_customerEmail_idx" ON "Booking"("customerEmail");
CREATE TABLE "Membership" ("id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "productId" TEXT NOT NULL, "memberUserId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT "ACTIVE", "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "creator" null NOT NULL, "product" null NOT NULL, "member" null NOT NULL);
CREATE UNIQUE INDEX "Membership_productId_memberUserId_key" ON "Membership"("productId","memberUserId");
CREATE INDEX "Membership_creatorId_status_idx" ON "Membership"("creatorId","status");
CREATE INDEX "Membership_memberUserId_status_idx" ON "Membership"("memberUserId","status");
CREATE TABLE "LessonProgress" ("id" TEXT NOT NULL PRIMARY KEY, "lessonId" TEXT NOT NULL, "userId" TEXT NOT NULL, "completed" BOOLEAN NOT NULL DEFAULT false, "progress" INTEGER NOT NULL, "lesson" null NOT NULL, "user" null NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "model" null NOT NULL, "id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "startsAt" TIMESTAMP(3) NOT NULL, "price" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT "INR", "published" BOOLEAN NOT NULL DEFAULT false, "creator" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "LessonProgress_lessonId_userId_key" ON "LessonProgress"("lessonId","userId");
CREATE INDEX "LessonProgress_userId_idx" ON "LessonProgress"("userId");
CREATE INDEX "LessonProgress_creatorId_startsAt_idx" ON "LessonProgress"("creatorId","startsAt");
CREATE TABLE "EventRegistration" ("id" TEXT NOT NULL PRIMARY KEY, "eventId" TEXT NOT NULL, "email" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT "REGISTERED", "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "event" null NOT NULL);
CREATE UNIQUE INDEX "EventRegistration_eventId_email_key" ON "EventRegistration"("eventId","email");
CREATE INDEX "EventRegistration_email_idx" ON "EventRegistration"("email");
CREATE TABLE "SaaSPlan" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "monthlyPrice" INTEGER NOT NULL, "yearlyPrice" INTEGER NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE "Subscription" ("id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "planId" TEXT NOT NULL, "provider" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT "ACTIVE", "user" null NOT NULL, "plan" null NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "Subscription_userId_status_idx" ON "Subscription"("userId","status");
CREATE INDEX "Subscription_providerSubscriptionId_idx" ON "Subscription"("providerSubscriptionId");
CREATE UNIQUE INDEX "Subscription_userId_planId_key" ON "Subscription"("userId","planId");
CREATE TABLE "CommunityConnection" ("id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "provider" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "creator" null NOT NULL);
CREATE UNIQUE INDEX "CommunityConnection_creatorId_provider_key" ON "CommunityConnection"("creatorId","provider");
CREATE TABLE "AnalyticsEvent" ("id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "type" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "creator" null NOT NULL);
CREATE INDEX "AnalyticsEvent_creatorId_createdAt_idx" ON "AnalyticsEvent"("creatorId","createdAt");
CREATE INDEX "AnalyticsEvent_creatorId_type_createdAt_idx" ON "AnalyticsEvent"("creatorId","type","createdAt");
CREATE INDEX "AnalyticsEvent_creatorId_path_createdAt_idx" ON "AnalyticsEvent"("creatorId","path","createdAt");
CREATE TABLE "EmailCampaign" ("id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "name" TEXT NOT NULL, "subject" TEXT NOT NULL, "body" TEXT NOT NULL, "segment" TEXT NOT NULL DEFAULT "ALL", "status" TEXT NOT NULL DEFAULT "DRAFT", "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "creator" null NOT NULL);
CREATE INDEX "EmailCampaign_creatorId_status_idx" ON "EmailCampaign"("creatorId","status");
CREATE INDEX "EmailCampaign_creatorId_createdAt_idx" ON "EmailCampaign"("creatorId","createdAt");
CREATE TABLE "EmailAutomation" ("id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "name" TEXT NOT NULL, "trigger" TEXT NOT NULL, "subject" TEXT NOT NULL, "body" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "creator" null NOT NULL);
CREATE INDEX "EmailAutomation_creatorId_trigger_enabled_idx" ON "EmailAutomation"("creatorId","trigger","enabled");
CREATE TABLE "EmailAutomationStep" ("id" TEXT NOT NULL PRIMARY KEY, "automationId" TEXT NOT NULL, "position" INTEGER NOT NULL, "delayHours" INTEGER NOT NULL, "subject" TEXT NOT NULL, "body" TEXT NOT NULL, "automation" null NOT NULL);
CREATE INDEX "EmailAutomationStep_automationId_position_idx" ON "EmailAutomationStep"("automationId","position");
CREATE TABLE "EmailDelivery" ("id" TEXT NOT NULL PRIMARY KEY, "recipientEmail" TEXT NOT NULL, "subject" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT "SENT", "sentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "EmailDelivery_campaignId_status_idx" ON "EmailDelivery"("campaignId","status");
CREATE INDEX "EmailDelivery_recipientEmail_sentAt_idx" ON "EmailDelivery"("recipientEmail","sentAt");
CREATE TABLE "EmailUnsubscribe" ("id" TEXT NOT NULL PRIMARY KEY, "creatorId" TEXT NOT NULL, "email" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "creator" null NOT NULL);
CREATE UNIQUE INDEX "EmailUnsubscribe_creatorId_email_key" ON "EmailUnsubscribe"("creatorId","email");
CREATE INDEX "EmailUnsubscribe_email_idx" ON "EmailUnsubscribe"("email");
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "CreatorProfile" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "CreatorProfile" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_moduleId_fkey" FOREIGN KEY ("moduleId") REFERENCES "CourseModule" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_leadMagnetId_fkey" FOREIGN KEY ("leadMagnetId") REFERENCES "LeadMagnet" ("id") ON DELETE SetNull ON UPDATE CASCADE;
ALTER TABLE "LeadMagnet" ADD CONSTRAINT "LeadMagnet_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "BookingSlot" ADD CONSTRAINT "BookingSlot_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_slotId_fkey" FOREIGN KEY ("slotId") REFERENCES "BookingSlot" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "LessonProgress" ADD CONSTRAINT "LessonProgress_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "LessonProgress" ADD CONSTRAINT "LessonProgress_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "LessonProgress" ADD CONSTRAINT "LessonProgress_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "EventRegistration" ADD CONSTRAINT "EventRegistration_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "Event" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_planId_fkey" FOREIGN KEY ("planId") REFERENCES "SaaSPlan" ("id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "CommunityConnection" ADD CONSTRAINT "CommunityConnection_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "EmailCampaign" ADD CONSTRAINT "EmailCampaign_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "EmailAutomation" ADD CONSTRAINT "EmailAutomation_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "EmailAutomationStep" ADD CONSTRAINT "EmailAutomationStep_automationId_fkey" FOREIGN KEY ("automationId") REFERENCES "EmailAutomation" ("id") ON DELETE Cascade ON UPDATE CASCADE;
ALTER TABLE "EmailDelivery" ADD CONSTRAINT "EmailDelivery_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "EmailCampaign" ("id") ON DELETE SetNull ON UPDATE CASCADE;
ALTER TABLE "EmailUnsubscribe" ADD CONSTRAINT "EmailUnsubscribe_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User" ("id") ON DELETE Cascade ON UPDATE CASCADE;
