import {NextResponse} from "next/server";
import {getCurrentUser} from "@/lib/auth";
import {prisma} from "@/lib/prisma";
const allowedActions=["WEBHOOK_POST","GOOGLE_SHEETS_APPEND","SLACK_WEBHOOK","DISCORD_WEBHOOK","TELEGRAM_SEND","EMAIL_SEND"];
const allowedTriggers=["LEAD_CREATED","ORDER_PAID","BOOKING_CREATED","BOOKING_PAID","EVENT_REGISTERED","MEMBERSHIP_ACTIVATED"];
function safeStep(s:any,i:number){return {position:i,action:String(s.action||""),config:s.config&&typeof s.config==="object"?s.config:{},enabled:s.enabled!==false};}
export async function GET(){const u=await getCurrentUser();if(!u)return NextResponse.json({error:"Authentication required."},{status:401});const rows=await prisma.automation.findMany({where:{creatorId:u.id},include:{steps:{orderBy:{position:"asc"}},connection:{select:{id:true,name:true,provider:true,status:true}}},orderBy:{createdAt:"desc"}});return NextResponse.json({automations:rows});}
export async function POST(req:Request){const u=await getCurrentUser();if(!u)return NextResponse.json({error:"Authentication required."},{status:401});const b=await req.json();const trigger=String(b.trigger||"").toUpperCase();const steps=Array.isArray(b.steps)?b.steps.map(safeStep):[];if(!ALLOWED(trigger,allowedTriggers)||!steps.length||steps.some((s:any)=>!allowedActions.includes(s.action)))return NextResponse.json({error:"Invalid automation trigger or actions."},{status:400});const connectionId=b.connectionId?String(b.connectionId):null;if(connectionId){const c=await prisma.integrationConnection.findFirst({where:{id:connectionId,creatorId:u.id}});if(!c)return NextResponse.json({error:"Integration connection not found."},{status:404});}const row=await prisma.automation.create({data:{creatorId:u.id,name:String(b.name||"New automation").trim().slice(0,100),trigger,status:"ACTIVE",conditions:b.conditions&&typeof b.conditions==="object"?b.conditions:undefined,connectionId,steps:{create:steps.map((s:any)=>({position:s.position,action:s.action,config:s.config,enabled:s.enabled}))}} ,include:{steps:true}});return NextResponse.json({automation:row},{status:201});}
export async function PATCH(req:Request){const u=await getCurrentUser();if(!u)return NextResponse.json({error:"Authentication required."},{status:401});const b=await req.json();const id=String(b.id||"");const a=await prisma.automation.findFirst({where:{id,creatorId:u.id}});if(!a)return NextResponse.json({error:"Automation not found."},{status:404});const data:any={};if(b.name!==undefined)data.name=String(b.name).trim().slice(0,100);if(b.status!==undefined&&["ACTIVE","PAUSED"].includes(String(b.status).toUpperCase()))data.status=String(b.status).toUpperCase();if(b.conditions!==undefined)data.conditions=b.conditions;if(b.connectionId!==undefined)data.connectionId=b.connectionId||null;if(Array.isArray(b.steps)){await prisma.automationStep.deleteMany({where:{automationId:id}});data.steps={create:b.steps.map(safeStep).map((s:any)=>({position:s.position,action:s.action,config:s.config,enabled:s.enabled}))};}const row=await prisma.automation.update({where:{id},data,include:{steps:true}});return NextResponse.json({automation:row});}
export async function DELETE(req:Request){const u=await getCurrentUser();if(!u)return NextResponse.json({error:"Authentication required."},{status:401});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Automation id is required."},{status:400});await prisma.automation.deleteMany({where:{id,creatorId:u.id}});return NextResponse.json({success:true});}
function ALLOWED(value:string,values:string[]){return values.includes(value);}
